<?php
/*
 * All Vars in this file are:
 * - Required = true
 * - Editable = true
 * - Scope = global
 *
 *
*/

return [
    [
        "key"         => "APP_NAME",
        "label"       => "Brand Name (En)",
        "type"        => "text",
        "group"       => "General",
        "required"    => true,
        "editable"    => true,
        "scope"       => "global",
        "description" => null,
    ],
    [
        "key"         => "APP_NAME_AR",
        "label"       => "Brand Name (Ar)",
        "type"        => "text",
        "group"       => "General",
        "required"    => true,
        "editable"    => true,
        "scope"       => "global",
        "description" => null,
    ],
    [
        "key"         => "ONLINE_EMAIL",
        "label"       => "Contact Email",
        "type"        => "email",
        "group"       => "General",
        "required"    => true,
        "editable"    => true,
        "scope"       => "global",
        "description" => null,
    ],
    [
        "key"         => "INFO_EMAIL",
        "label"       => "Info Email",
        "type"        => "email",
        "group"       => "General",
        "required"    => true,
        "editable"    => true,
        "scope"       => "global",
        "description" => null,
    ],
    [
        "key"         => "HOTPHONE",
        "label"       => "Hot Line",
        "type"        => "text",
        "group"       => "General",
        "required"    => true,
        "editable"    => true,
        "scope"       => "global",
        "description" => null,
    ],
    [
        "key"         => "SOCIAL_URL_FACEBOOK",
        "label"       => "SOCIAL_URL_FACEBOOK",
        'type'        => 'url',
        "group"       => "General",
        "scope"       => "global",
        "required"    => true,
        "editable"    => false,
        "description" => null,
    ],
    [
        "key"         => "SOCIAL_URL_YOUTUBE",
        "label"       => "SOCIAL_URL_YOUTUBE",
        'type'        => 'url',
        "group"       => "General",
        "scope"       => "global",
        "required"    => true,
        "editable"    => false,
        "description" => null,
    ],
    [
        "key"         => "SOCIAL_URL_INSTAGRAM",
        "label"       => "SOCIAL_URL_INSTAGRAM",
        'type'        => 'url',
        "group"       => "General",
        "scope"       => "global",
        "required"    => true,
        "editable"    => false,
        "description" => null,
    ],
    [
        "key"         => "STORE_ANDROID_URL",
        "label"       => "STORE_ANDROID_URL",
        'type'        => 'url',
        "group"       => "General",
        "scope"       => "global",
        "required"    => true,
        "editable"    => false,
        "description" => null,
    ],
    [
        "key"         => "STORE_APPLE_URL",
        "label"       => "STORE_APPLE_URL",
        'type'        => 'url',
        "group"       => "General",
        "scope"       => "global",
        "required"    => true,
        "editable"    => false,
        "description" => null,
    ],
    [
        "key"         => "STORE_HWAWEI_URL",
        "label"       => "STORE_HWAWEI_URL",
        'type'        => 'url',
        "group"       => "General",
        "scope"       => "global",
        "required"    => true,
        "editable"    => false,
        "description" => null,
    ],
    [
        "key"         => "LOGO_IMAGE_URL",
        "label"       => "Logo (En)",
        'type'        => 'url',
        "group"       => "General",
        "required"    => true,
        "editable"    => false,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "TRUCK_IMAGE_URL",
        "label"       => "TRUCK_IMAGE_URL",
        'type'        => 'url',
        "group"       => "General",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "ADMIN_URL",
        "label"       => "ADMIN_URL",
        "type"        => "url",
        "group"       => "General",
        "required"    => true,
        "editable"    => false,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "WEBSITE_URL",
        "label"       => "WEBSITE_URL",
        "type"        => "url",
        "group"       => "General",
        "required"    => true,
        "editable"    => false,
        "scope"       => "global",
        "description" => null,
    ],
    [
        "key"         => "APP_URL",
        "label"       => "APP_URL",
        "type"        => "url",
        "group"       => "General",
        "required"    => true,
        "editable"    => false,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "PRODUCT_TYPE",
        "label"       => "PRODUCT_TYPE",
        "type"        => "single_select",
        "group"       => "Ecommerce",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "options"     => '[{"main" : "Main"},{"variant" : "Variant"}]',
        "description" => null,
    ],
    [
        "key"         => "BRANCH_TYPES",
        "label"       => "BRANCH_TYPES",
        "type"        => "text",
        "group"       => "Ecommerce",
        "required"    => true,
        "editable"    => false,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "COLORED_LOGO_EN",
        "label"       => "Colored Logo (En)",
        "group"       => "Brand",
        "required"    => 1,
        "editable"    => 1,
        "type"        => "image",
        "scope"       => "global",
        "description" => null,
    ],
    [
        "key"         => "COLORED_LOGO_AR",
        "label"       => "Colored Logo (Ar)",
        "group"       => "Brand",
        "required"    => 1,
        "editable"    => 1,
        "type"        => "image",
        "scope"       => "global",
        "description" => null,
    ],
    [
        "key"         => "WHITE_LOGO_EN",
        "label"       => "White Logo (En)",
        "group"       => "Brand",
        "required"    => 1,
        "editable"    => 1,
        "type"        => "image",
        "scope"       => "global",
        "description" => null,
    ],
    [
        "key"         => "WHITE_LOGO_AR",
        "label"       => "White Logo (Ar)",
        "group"       => "Brand",
        "required"    => 1,
        "editable"    => 1,
        "type"        => "image",
        "scope"       => "global",
        "description" => null,
    ],
    [
        "key"         => "BLACK_LOGO",
        "label"       => "Black & White Logo",
        "group"       => "Brand",
        "required"    => 1,
        "editable"    => 1,
        "type"        => "image",
        "scope"       => "admin",
        "description" => null,
    ],
    [
        "key"         => "FAV_ICON",
        "label"       => "Fav Icon",
        "group"       => "Brand",
        "required"    => 1,
        "editable"    => 1,
        "type"        => "image",
        "scope"       => "global",
        "description" => null,
    ],
];
