<?php

return [
    [
        "key"         => "APP_KEY",
        "label"       => "APP_KEY",
        "type"        => "text",
        "group"       => "General",
        "required"    => true,
        "editable"    => false,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "MAIL_DRIVER",
        "label"       => "Mail Driver",
        "type"        => "text",
        "group"       => "Mail",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "MAIL_HOST",
        "label"       => "Mail Host",
        "type"        => "text",
        "group"       => "Mail",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "MAIL_PORT",
        "label"       => "Mail Port",
        "type"        => "number",
        "group"       => "Mail",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "MAIL_USERNAME",
        "label"       => "Mail Username",
        "type"        => "text",
        "group"       => "Mail",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "MAIL_PASSWORD",
        "label"       => "Mail Password",
        "type"        => "text",
        "group"       => "Mail",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "MAIL_ENCRYPTION",
        "label"       => "Mail Encryption",
        "type"        => "text",
        "group"       => "Mail",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "MAIL_FROM_ADDRESS",
        "label"       => "Sender Email Address",
        "type"        => "email",
        "group"       => "Mail",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "MAIL_FROM_NAME",
        "label"       => "Sender Email Name",
        "type"        => "text",
        "group"       => "Mail",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "MAILCHIMP_APIKEY",
        "label"       => "Mailchimp API Key",
        "type"        => "text",
        "group"       => "MailChimp",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "MAILCHIMP_LIST_ID",
        "label"       => "Mailchimp List ID",
        "type"        => "text",
        "group"       => "MailChimp",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "FACEBOOK_CLIENT_ID",
        "label"       => "Facebook Client ID",
        "type"        => "text",
        "group"       => "Social Auth",
        "required"    => true,
        "editable"    => true,
        "scope"       => "global",
        "description" => null,
    ],
    [
        "key"         => "FACEBOOK_CLIENT_SECRET",
        "label"       => "Facebook Client Secret",
        "type"        => "text",
        "group"       => "Social Auth",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "GOOGLE_CLIENT_ID",
        "label"       => "Google Client ID",
        "type"        => "text",
        "group"       => "Social Auth",
        "required"    => true,
        "editable"    => true,
        "scope"       => "global",
        "description" => null,
    ],
    [
        "key"         => "GOOGLE_CLIENT_SECRET",
        "label"       => "Google Client Secret",
        "type"        => "text",
        "group"       => "Social Auth",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "GOOGLE_REDIRECT",
        "label"       => "Google Redirect URL",
        "type"        => "text",
        "group"       => "Social Auth",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "ARAMEX_USER_NAME",
        "label"       => "Aramex Username",
        "type"        => "text",
        "group"       => "Aramex",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "ARAMEX_PASSWORD",
        "label"       => "Aramex Password",
        "type"        => "text",
        "group"       => "Aramex",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "ARAMEX_ACCOUNT_ENTITY",
        "label"       => "Aramex Account Entity",
        "type"        => "text",
        "group"       => "Aramex",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "ARAMEX_ACCOUNT_COUNTRY_CODE",
        "label"       => "Aramex Account Country Code",
        "type"        => "text",
        "group"       => "Aramex",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "ARAMEX_URL",
        "label"       => "Aramex URL",
        "type"        => "text",
        "group"       => "Aramex",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "ARAMEX_ACCOUNT_PIN_1",
        "label"       => "Aramex Account PIN 1",
        "type"        => "text",
        "group"       => "Aramex",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "ARAMEX_ACCOUNT_NUMBER_1",
        "label"       => "Aramex Account No 1",
        "type"        => "text",
        "group"       => "Aramex",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "ARAMEX_ACCOUNT_PIN_2",
        "label"       => "Aramex Account PIN 2",
        "type"        => "text",
        "group"       => "Aramex",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "ARAMEX_ACCOUNT_NUMBER_2",
        "label"       => "Aramex Account No 2",
        "type"        => "text",
        "group"       => "Aramex",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "MERCHANT_ID",
        "label"       => "Paymob Merchant ID",
        "type"        => "text",
        "group"       => "Paymob",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "WE_ACCEPT_PAYMENT_API_KEY",
        "label"       => "Paymob API Key",
        "type"        => "text",
        "group"       => "Paymob",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "MEZA_SECURE_KEY",
        "label"       => "Meza Secure Key",
        "type"        => "text",
        "group"       => "Meza",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "MEZA_MERCHANT_ID",
        "label"       => "Meza Merchant ID",
        "type"        => "text",
        "group"       => "Meza",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "MEZA_TERMINAL_ID",
        "label"       => "Meza Terminal ID",
        "type"        => "text",
        "group"       => "Meza",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "NBE_BASE_URL",
        "label"       => "NBE Base Url",
        "type"        => "text",
        "group"       => "NBE",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "NBE_USERNAME",
        "label"       => "NBE Username",
        "type"        => "text",
        "group"       => "NBE",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "NBE_PASSWORD",
        "label"       => "NBE Password",
        "type"        => "text",
        "group"       => "NBE",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "NBE_MERCHANT_ID",
        "label"       => "NBE Merchant ID",
        "type"        => "text",
        "group"       => "NBE",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "QNB_BASE_URL",
        "label"       => "QNB Base Url",
        "type"        => "text",
        "group"       => "QNB",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "QNB_GATEWAY_URL",
        "label"       => "QNB Gateway Url",
        "type"        => "text",
        "group"       => "QNB",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "NBE_GATEWAY_URL",
        "label"       => "NBE Gateway Url",
        "type"        => "text",
        "group"       => "NBE",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "NBE_CHECKOUT_JS",
        "label"       => "NBE Checkout js",
        "type"        => "text",
        "group"       => "NBE",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "PAYTABS_CALLBACK_URL",
        "label"       => "Paytabs Callback Url",
        "type"        => "text",
        "group"       => "Paytabs",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "PAYTABS_SERVER_KEY",
        "label"       => "Paytabs Server Key",
        "type"        => "text",
        "group"       => "Paytabs",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "PAYTABS_PROFILE_ID",
        "label"       => "Paytabs Profile ID",
        "type"        => "text",
        "group"       => "Paytabs",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "HMAC_HASH",
        "label"       => "Paymob HMAC Hash",
        "type"        => "text",
        "group"       => "Paymob",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "GET_GO_IFRAME_ID",
        "label"       => "Get Go IFrame ID",
        "type"        => "text",
        "group"       => "Paymob",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "GET_GO_INTEGRATION_ID",
        "label"       => "Get Go Integration ID",
        "type"        => "text",
        "group"       => "Paymob",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "PREMIUM_IFRAME_ID",
        "label"       => "Premium IFrame ID",
        "type"        => "text",
        "group"       => "Paymob",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "PREMIUM_INTEGRATION_ID",
        "label"       => "Premium Integration ID",
        "type"        => "text",
        "group"       => "Paymob",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "SHAHRY_IFRAME_ID",
        "label"       => "Shahry IFrame ID",
        "type"        => "text",
        "group"       => "Paymob",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "SHAHRY_INTEGRATION_ID",
        "label"       => "Shahry Integration ID",
        "type"        => "text",
        "group"       => "Paymob",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "SOUHOOLA_IFRAME_ID",
        "label"       => "Souhoola IFrame ID",
        "type"        => "text",
        "group"       => "Paymob",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "SOUHOOLA_INTEGRATION_ID",
        "label"       => "Souhoola Integration ID",
        "type"        => "text",
        "group"       => "Paymob",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "VALU_IFRAME_ID",
        "label"       => "VALU IFrame ID",
        "type"        => "text",
        "group"       => "Paymob",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "VALU_INTEGRATION_ID",
        "label"       => "VALU Integration ID",
        "type"        => "text",
        "group"       => "Paymob",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "VODAFONE_IFRAME_ID",
        "label"       => "Vodafone IFrame ID",
        "type"        => "text",
        "group"       => "Paymob",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "VODAFONE_INTEGRATION_ID",
        "label"       => "Vodafone Integration ID",
        "type"        => "text",
        "group"       => "Paymob",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "WE_ACCEPT_IFRAME_ID",
        "label"       => "We Accept IFrame ID",
        "type"        => "text",
        "group"       => "Paymob",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "WE_ACCEPT_INTEGRATION_ID",
        "label"       => "We Accept Integration ID",
        "type"        => "text",
        "group"       => "Paymob",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "UPG_MERCHANT_ID",
        "label"       => "UPG Merchant ID",
        "type"        => "text",
        "group"       => "UPG",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "UPG_TERMINAL_ID",
        "label"       => "UPG Terminal ID",
        "type"        => "text",
        "group"       => "UPG",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "UPG_SECURE_KEY",
        "label"       => "UPG Secure Key",
        "type"        => "text",
        "group"       => "UPG",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "QNB_MERCHANT_ID",
        "label"       => "QNB Merchant ID",
        "type"        => "text",
        "group"       => "Bank Integration",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "QNB_USERNAME",
        "label"       => "QNB Username",
        "type"        => "text",
        "group"       => "Bank Integration",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "QNB_PASSWORD",
        "label"       => "QNB Password",
        "type"        => "text",
        "group"       => "Bank Integration",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "QNB_CHECKOUT_JS",
        "label"       => "QNB Checkout JS",
        "type"        => "text",
        "group"       => "Bank Integration",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "SMS_CONNECTION",
        "label"       => "SMS Connection",
        "type"        => "single_select",
        "group"       => "SMS",
        "required"    => false,
        "editable"    => true,
        "scope"       => "admin",
        "options"     => '[{"" : "Disabled"},{"victory" : "Victory"},{"smseg" : "SMSEG"},{"smsmisr" : "SMSMisr"}]',
        "description" => null,
    ],
    [
        "key"         => "SMS_DRIVER",
        "label"       => "SMS Driver",
        "type"        => "single_select",
        "group"       => "SMS",
        "required"    => false,
        "editable"    => true,
        "scope"       => "backend",
        "options"     => '[{"gateway" : "Gateway"},{"database" : "Database"}]',
        "description" => null,
    ],
    [
        "key"         => "SMS_USERNAME",
        "label"       => "SMS Username",
        "type"        => "text",
        "group"       => "SMS",
        "required"    => false,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "SMS_ID",
        "label"       => "SMS ID",
        "type"        => "text",
        "group"       => "SMS",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "SMS_MSIGNATURE",
        "label"       => "SMS Msignature",
        "type"        => "text",
        "group"       => "SMS",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "SMS_TOKEN",
        "label"       => "SMS token",
        "type"        => "text",
        "group"       => "SMS",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "SMS_PASSWORD",
        "label"       => "SMS Password",
        "type"        => "text",
        "group"       => "SMS",
        "required"    => false,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "SMS_SENDER_ID",
        "label"       => "SMS Sender ID",
        "type"        => "text",
        "group"       => "SMS",
        "required"    => false,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],

    [
        "key"         => "APPLE_REDIRECT_URI",
        "label"       => "Apple Redirect URI",
        "type"        => "text",
        "group"       => "Social Auth",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "APPLE_CLIENT_ID",
        "label"       => "Apple Client ID",
        "type"        => "text",
        "group"       => "Social Auth",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "APPLE_CLIENT_SECRET",
        "label"       => "Apple Client Secret",
        "type"        => "text",
        "group"       => "Social Auth",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "FCM_SERVER_KEY",
        "label"       => "FCM Server Key",
        "type"        => "text",
        "group"       => "FCM",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "FCM_SENDER_ID",
        "label"       => "FCM Sender ID",
        "type"        => "text",
        "group"       => "FCM",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "GOOGLE_MAP_API_KEY",
        "label"       => "Google Maps API Key",
        "type"        => "text",
        "group"       => "Google Maps",
        "required"    => true,
        "editable"    => true,
        "scope"       => "customer",
        "description" => null,
    ],
    [
        "key"         => "erp_token",
        "label"       => "ERP Token",
        "type"        => "text",
        "group"       => "ERP Settings",
        "required"    => false,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "QNB_SIMPLIFY_API_PUBLIC_KEY",
        "label"       => "QNB SIMPLIFY API PUBLIC KEY",
        "type"        => "text",
        "group"       => "QNB SIMPLIFY",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "QNB_SIMPLIFY_API_PRIVATE_KEY",
        "label"       => "QNB SIMPLIFY API PRIVATE KEY",
        "type"        => "text",
        "group"       => "QNB SIMPLIFY",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "METABASE_URL",
        "label"       => "Metabase URL",
        "type"        => "text",
        "group"       => "Metabase",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
    [
        "key"         => "METABASE_TOKEN",
        "label"       => "Metabase Token",
        "type"        => "text",
        "group"       => "Metabase",
        "required"    => true,
        "editable"    => true,
        "scope"       => "backend",
        "description" => null,
    ],
];
