<?php

return [
  [
      "key"         => "WEB_THEME_TYPE",
      "label"       => "WEB_THEME_TYPE",
      "group"       => "Web",
      "scope"       => "customer",
      "editable"    => false,
      "type"        => "number",
  ],
  [
      "key"         => "ENABLE_LOYALITY",
      "label"       => "ENABLE_LOYALITY",
      "group"       => "Web",
      "scope"       => "global",
      "type"        => "switch",
  ],
  [
      "key"         => "ENABLE_CATEGORY_VIEW",
      "label"       => "ENABLE_CATEGORY_VIEW",
      "group"       => "Web",
      "scope"       => "global",
      "type"        => "switch",
  ],
  [
      "key"         => "ENABLE_SUBCATEGORY_VIEW",
      "label"       => "ENABLE_SUBCATEGORY_VIEW",
      "group"       => "Web",
      "scope"       => "global",
      "type"        => "switch",
  ],
  [
      "key"         => "fbPixelId",
      "label"       => "fbPixelId",
      "group"       => "Web",
      "scope"       => "global",
      "type"        => "text",
  ],
  [
      "key"         => "googleTagManID",
      "label"       => "googleTagManID",
      "group"       => "Web",
      "scope"       => "global",
      "type"        => "text",
  ],
  [
      "key"         => "ENABLE_STATIC_MENU",
      "label"       => "ENABLE_STATIC_MENU",
      "group"       => "Web",
      "scope"       => "global",
      "type"        => "switch",
  ],
  [
      "key"         => "logoWidth",
      "label"       => "logoWidth",
      "group"       => "Web",
      "scope"       => "global",
      "type"        => "text",
  ],
  [
      "key"         => "logoHeight",
      "label"       => "logoHeight",
      "group"       => "Web",
      "scope"       => "global",
      "type"        => "text",
  ],
  [
      "key"         => "logoWidthMobile",
      "label"       => "logoWidthMobile",
      "group"       => "Web",
      "scope"       => "global",
      "type"        => "text",
  ],
  [
      "key"         => "logoHeightMobile",
      "label"       => "logoHeightMobile",
      "group"       => "Web",
      "scope"       => "global",
      "type"        => "text",
  ],
  [
      "key"         => "WEB_SEO_SCRIPTS",
      "label"       => "SEO Scripts",
      "group"       => "SEO Scripts",
      "scope"       => "global",
      "type"        => "textarea",
  ],
  [
      "key"         => "sloganEn",
      "label"       => "sloganEn",
      "group"       => "Web",
      "scope"       => "global",
      "type"        => "text",
  ],
  [
      "key"         => "sloganAr",
      "label"       => "sloganAr",
      "group"       => "Web",
      "scope"       => "global",
      "type"        => "text",
  ],
  [
      "key"         => "metaDescriptionEn",
      "label"       => "metaDescriptionEn",
      "group"       => "Web",
      "scope"       => "global",
      "type"        => "text",
  ],
  [
      "key"         => "metaDescriptionAr",
      "label"       => "metaDescriptionAr",
      "group"       => "Web",
      "scope"       => "global",
      "type"        => "text",
  ],
  [
      "key"         => "footerAboutCompanyEn",
      "label"       => "footerAboutCompanyEn",
      "group"       => "Web",
      "scope"       => "global",
      "type"        => "text",
  ],
  [
      "key"         => "footerAboutCompanyAr",
      "label"       => "footerAboutCompanyAr",
      "group"       => "Web",
      "scope"       => "global",
      "type"        => "text",
  ],
  [
      "key"         => "footerPaymentImages",
      "label"       => "Footer Payment Images",
      "group"       => "Web",
      "scope"       => "global",
      "type"        => "image",
  ],
  [
      "key"         => "footerPaymentImageStaticWidth",
      "label"       => "footerPaymentImageStaticWidth",
      "group"       => "Web",
      "scope"       => "global",
      "type"        => "text",
  ],
  [
      "key"         => "SOFTBAR_BG_COLOR",
      "label"       => "Soft Bar BG Color",
      "type"        => "color",
      "group"       => "Soft Bar",
      "required"    => false,
      "editable"    => true,
      "scope"       => "customer",
      "description" => null,
   ],
   [
      "key"         => "SOFTBAR_FONT_COLOR",
      "label"       => "Soft Bar Font Color",
      "type"        => "color",
      "group"       => "Soft Bar",
      "required"    => false,
      "editable"    => true,
      "scope"       => "customer",
      "description" => null,
   ],
   [
      "key"         => "SOFTBAR_TEXT_EN",
      "label"       => "Soft Bar Text (EN)",
      "type"        => "text",
      "group"       => "Soft Bar",
      "required"    => false,
      "editable"    => true,
      "scope"       => "customer",
      "description" => null,
   ],
   [
      "key"         => "SOFTBAR_TEXT_AR",
      "label"       => "Soft Bar Text (AR)",
      "type"        => "text",
      "group"       => "Soft Bar",
      "required"    => false,
      "editable"    => true,
      "scope"       => "customer",
      "description" => null,
   ],
   [
      "key"         => "ENABLE_SOFTBAR",
      "label"       => "Enable Soft Bar",
      "type"        => "switch",
      "group"       => "Soft Bar",
      "required"    => false,
      "editable"    => true,
      "scope"       => "customer",
      "description" => null,
   ],
   [
      "key"         => "ENABLE_LARGE_IMAGE",
      "label"       => "Enable Large Image",
      "type"        => "switch",
      "group"       => "Web",
      "required"    => false,
      "editable"    => true,
      "scope"       => "customer",
      "description" => null,
   ],
   [
      "key"         => "ORDER_POLICY_TEXT_EN",
      "label"       => "Order Policy Text En",
      "type"        => "html",
      "group"       => "Web",
      "required"    => true,
      "editable"    => true,
      "scope"       => "customer",
      "description" => null,
   ],
   [
      "key"         => "ORDER_POLICY_TEXT_AR",
      "label"       => "Order Policy Text Ar",
      "type"        => "html",
      "group"       => "Web",
      "required"    => true,
      "editable"    => true,
      "scope"       => "customer",
      "description" => null,
   ],
   [
      "key"         => "enablePhoneLogin",
      "label"       => "Enable Phone Login",
      "type"        => "switch",
      "group"       => "Web",
      "required"    => false,
      "editable"    => true,
      "scope"       => "customer",
      "description" => null,
   ],
];
